FROM golang:latest
WORKDIR /weilun_BE
COPY . .
ENV accessToken=

ENV refreshToken=
ENV dbIP=
ENV dbPort=
ENV dbUser=
ENV dbPwd=
ENV dbName=
ENV dbType=
ENV version=

RUN go mod download
RUN go build -o main .
EXPOSE 8080
CMD ["./main"]