// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package utils

import (
	"github.com/google/wire"
	"github.com/jackc/pgx/v5"
	"main/controller"
	"main/service"
	"main/sql"
)

// Injectors from wire.go:

func Init(q *db.Queries, conn *pgx.Conn) *controller.AppControllerImpl {
	userServImpl := service.UserServInit(q, conn)
	cmpServImpl := service.CmpServInit(q, conn)
	appService := service.AppServiceInit(userServImpl, cmpServImpl)
	userCtrlImpl := controller.UserCtrlInit(appService)
	authCtrlImpl := controller.AuthCtrlInit(appService)
	appControllerImpl := controller.AppControllerInit(userCtrlImpl, authCtrlImpl)
	return appControllerImpl
}

// wire.go:

var cmpServSet = wire.NewSet(service.CmpServInit, wire.Bind(new(service.CmpServ), new(*service.CmpServImpl)))

var userServSet = wire.NewSet(service.UserServInit, wire.Bind(new(service.UserServ), new(*service.UserServImpl)))

var userCtrlSet = wire.NewSet(controller.UserCtrlInit, wire.Bind(new(controller.UserCtrl), new(*controller.UserCtrlImpl)))

var authCtrlSet = wire.NewSet(controller.AuthCtrlInit, wire.Bind(new(controller.AuthCtrl), new(*controller.AuthCtrlImpl)))
