// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiregen

import (
	sql2 "database/sql"
	"github.com/google/wire"
	"main/controller"
	"main/middleware"
	"main/service"
	"main/sql"
)

// Injectors from wire.go:

func Init(q *sql.Queries, conn *sql2.DB) *controller.AppControllerImpl {
	userServImpl := service.UserServInit(q, conn)
	cmpServImpl := service.CmpServInit(q, conn)
	jobsServImpl := service.JobsServInit(q, conn)
	repairServImpl := service.RepairServInit(q, conn)
	alertServImpl := service.AlertServInit(q, conn)
	revenueServImpl := service.RevenueServInit(q, conn)
	gasServImpl := service.GasServInit(q, conn)
	appService := service.AppServiceInit(userServImpl, cmpServImpl, jobsServImpl, repairServImpl, alertServImpl, revenueServImpl, gasServImpl)
	userCtrlImpl := controller.UserCtrlInit(appService)
	authCtrlImpl := controller.AuthCtrlInit(appService)
	cmpCtrlImpl := controller.CmpCtrlInit(appService)
	jobsCtrlImpl := controller.JobsCtrlInit(appService)
	repairCtrlImpl := controller.RepairCtrlInit(appService)
	alertCtrlImpl := controller.AlertCtrlInit(appService)
	socketCtrlImpl := controller.SocketCtrlInit(appService)
	revenueCtrlImpl := controller.RevenueCtrlInit(appService)
	gasCtrlImpl := controller.GasCtrlInit(appService)
	appControllerImpl := controller.AppControllerInit(userCtrlImpl, authCtrlImpl, cmpCtrlImpl, jobsCtrlImpl, repairCtrlImpl, alertCtrlImpl, socketCtrlImpl, revenueCtrlImpl, gasCtrlImpl)
	return appControllerImpl
}

func MInit(q *sql.Queries, conn *sql2.DB) *middleware.AppMiddlewareImpl {
	userServImpl := service.UserServInit(q, conn)
	cmpServImpl := service.CmpServInit(q, conn)
	jobsServImpl := service.JobsServInit(q, conn)
	repairServImpl := service.RepairServInit(q, conn)
	alertServImpl := service.AlertServInit(q, conn)
	revenueServImpl := service.RevenueServInit(q, conn)
	gasServImpl := service.GasServInit(q, conn)
	appService := service.AppServiceInit(userServImpl, cmpServImpl, jobsServImpl, repairServImpl, alertServImpl, revenueServImpl, gasServImpl)
	roleMidImpl := middleware.RoleMidInit(appService)
	appMiddlewareImpl := middleware.AppMiddlewareInit(roleMidImpl)
	return appMiddlewareImpl
}

// wire.go:

var alertServSet = wire.NewSet(service.AlertServInit, wire.Bind(new(service.AlertServ), new(*service.AlertServImpl)))

var revenueServSet = wire.NewSet(service.RevenueServInit, wire.Bind(new(service.RevenueServ), new(*service.RevenueServImpl)))

var cmpServSet = wire.NewSet(service.CmpServInit, wire.Bind(new(service.CmpServ), new(*service.CmpServImpl)))

var jobsServSet = wire.NewSet(service.JobsServInit, wire.Bind(new(service.JobsServ), new(*service.JobsServImpl)))

var userServSet = wire.NewSet(service.UserServInit, wire.Bind(new(service.UserServ), new(*service.UserServImpl)))

var repairServSet = wire.NewSet(service.RepairServInit, wire.Bind(new(service.RepairServ), new(*service.RepairServImpl)))

var gasServSet = wire.NewSet(service.GasServInit, wire.Bind(new(service.GasServ), new(*service.GasServImpl)))

var revenueCtrlSet = wire.NewSet(controller.RevenueCtrlInit, wire.Bind(new(controller.RevenueCtrl), new(*controller.RevenueCtrlImpl)))

var userCtrlSet = wire.NewSet(controller.UserCtrlInit, wire.Bind(new(controller.UserCtrl), new(*controller.UserCtrlImpl)))

var alertCtrlSet = wire.NewSet(controller.AlertCtrlInit, wire.Bind(new(controller.AlertCtrl), new(*controller.AlertCtrlImpl)))

var jobsCtrlSet = wire.NewSet(controller.JobsCtrlInit, wire.Bind(new(controller.JobsCtrl), new(*controller.JobsCtrlImpl)))

var authCtrlSet = wire.NewSet(controller.AuthCtrlInit, wire.Bind(new(controller.AuthCtrl), new(*controller.AuthCtrlImpl)))

var cmpCtrlSet = wire.NewSet(controller.CmpCtrlInit, wire.Bind(new(controller.CmpCtrl), new(*controller.CmpCtrlImpl)))

var repairCtrlSet = wire.NewSet(controller.RepairCtrlInit, wire.Bind(new(controller.RepairCtrl), new(*controller.RepairCtrlImpl)))

var gasCtrlSet = wire.NewSet(controller.GasCtrlInit, wire.Bind(new(controller.GasCtrl), new(*controller.GasCtrlImpl)))

var socketCtrlSet = wire.NewSet(controller.SocketCtrlInit, wire.Bind(new(controller.SocketCtrl), new(*controller.SocketCtrlImpl)))

var roleMidSet = wire.NewSet(middleware.RoleMidInit, wire.Bind(new(middleware.RoleMid), new(*middleware.RoleMidImpl)))
